### ISSUE TITLE
gdas_utility to generate Pangu-Weather model inputs

### ISSUE THREAD

**Issue by SadeghTabas-NOAA** [NOAA-EMC/Pangu-Weather#2]
In this issue we will implement a utility to generate inputs for Pangu-Weather model from GDAS data. The realtime GDAS data will be downloaded and converted from grib2 format to Pangu-Weather model desired format. The script would be similar to [gdas_utility.py](https://github.com/NOAA-EMC/graphcast/blob/main/NCEP/gdas_utility.py)

**Comment by LinlinCui-NOAA** [comment]
@SadeghTabas-NOAA When looking at sample input data, it only needs one time step (f000), and separates surface variables and pressure level variables into two files. The format is numpy's npy.

**Comment by SadeghTabas-NOAA** [comment]
> @SadeghTabas-NOAA When looking at sample input data, it only needs one time step (f000), and separates surface variables and pressure level variables into two files. The format is numpy's npy.

That's fine, please update the `gdas_utility.py` for this one based on their inputs.
